### ISSUE TITLE
River network from HydroSHEDS

### ISSUE THREAD

**Issue by solomonsg** [nmizukami/mizuRoute#18]
Hi all, 

I have a global runoff data and the NHDFlowliine seems available for the US. is there any way to use mizuRoute using other rivernetworks such as from HydroSHEDS https://www.hydrosheds.org/downloads 

Best regards,
Solomon

**Comment by nmizukami** [comment]
Hi Solomon,

Yes, it is possible to use HydroSHEDS for mizuRoute.  It is necessary to create river network data in input format (see https://mizuroute.readthedocs.io/en/develop/ or look at example of testCase data).

Now I don't have official git repo that stores pre-processing scripts for dataset (river network or/and runoff mapping) required for mizuRoute, but I would be happy to share less generic python scripts I have to start with.  

However, I expect some challenge with applying HydroSHEDS to the entire global domain.  The largest dataset I have tried so far is NHDPlus data over CONUS (2.7 million reaches).

**Comment by solomonsg** [comment]
Hi nmizukami, 

That would be great if you can send me the python scripts to prepare the HydroSHEDS to the format required by mizuRoute, I will try it first for some basins in Asia and Africa. Thanks and this is my email shg1f19@soton.ac.uk   
Best regards, 


Solomon

**Comment by solomonsg** [comment]
Hi Naoki,

Thanks for the information. If you think it's possible I am planning to use HydroSHEDS (catchment and river network) as input for MizuRoute for some basins in Asia and Africa.
What I have now is,

1.       Catchment shapefile  (with COMID, i.e. basin ID)

2.       River network (with the following information)



[cid:image001.png@01D6983C.BCCE6170]

3.       Daily runoff data (NetCDF)

I have already installed mizuRoute and read the instructions and your paper, but it would be great if you can send me your python scripts to convert the catchment/river network and runoff to the format required by MizuRoute.

Thanks a lot again.

Best regards,

Solomon
